// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('starter.controllers', []).controller('AppCtrl', function($scope, $ionicModal, $timeout) {
    $scope.loginData = {};
    $ionicModal.fromTemplateUrl('templates/login.html', {
      scope: $scope
    }).then(function(modal) {
      $scope.modal = modal;
    });
    $scope.closeLogin = function() {
      $scope.modal.hide();
    };
    $scope.login = function() {
      $scope.modal.show();
    };
    $scope.doLogin = function() {
      console.log('Doing login', $scope.loginData);
      $timeout((function() {
        $scope.closeLogin();
      }), 1000);
    };
  }).controller('PlaylistsCtrl', function($scope) {
    $scope.playlists = [
      {
        title: 'Reggae',
        id: 1
      }, {
        title: 'Chill',
        id: 2
      }, {
        title: 'Dubstep',
        id: 3
      }, {
        title: 'Indie',
        id: 4
      }
    ];
  }).controller('PlaylistCtrl', function($scope, $stateParams) {});

}).call(this);

//# sourceMappingURL=controllers.js.map
